### ISSUE TITLE
範囲外の数字が表示される

### ISSUE THREAD

**Issue by 10mocy** [Siketyan/Bingo#1]
通常のビンゴで利用される数字は、1〜75です。

**Comment by siketyan** [comment]
要件定義案件

![image](https://user-images.githubusercontent.com/12772118/56080878-86440280-5e41-11e9-9241-b3fa9c7c6746.png)

**Comment by 10mocy** [comment]
## Checklist
- [x] 仕様で書いておいたほうがいいかも
